scheduler_id: "12D3KooWQER7HEpwsvqSzqzaiV36d3Bn6DZrnwEunnzS76pgZkMU"
send_metrics: true
available_datasets:
  ethereum-mainnet: "czM6Ly9ldGhlcmV1bS1tYWlubmV0"
  binance-mainnet: "czM6Ly9ic2MtbWFpbm5ldA"
  base-mainnet: "czM6Ly9iYXNlLW1haW5uZXQ"
  moonbeam-mainnet: "czM6Ly9tb29uYmVhbS1tYWlubmV0"
